steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cognitive-app-1:$COMMIT_SHA', './app1']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cognitive-app-1:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--verbose'
  - '--filename=kube/app1-kservice.yaml'
  - '--image=gcr.io/$PROJECT_ID/cognitive-app-1:$COMMIT_SHA'
  - '--cluster=poc-cluster'
  - '--location=us-central1-b'
  - '--output=output1'


  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cognitive-app-2:$COMMIT_SHA', './app2']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cognitive-app-2:$COMMIT_SHA']
  # deploy container service app2
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--verbose'
  - '--filename=kube/app2-kservice.yaml'
  - '--image=gcr.io/$PROJECT_ID/cognitive-app-2:$COMMIT_SHA'
  - '--cluster=poc-cluster'
  - '--location=us-central1-b'
  - '--output=output2'


  # deploy container gateway
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--filename=kube/gateway.yaml'
  - '--cluster=poc-cluster'
  - '--location=us-central1-b'
  - '--output=output3'