apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app1-knative
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: gcr.io/poc-orquestador/cognitive-app-1
