apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app1
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: gcr.io/poc-lanzarote/cognitive-app-1:bc166a401e185e7e171f7e336dc96e4fbab66722
