apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: portal-entry-route
  namespace: default
spec:
  gateways:
  - knative-ingress-gateway.knative-serving.svc.cluster.local
  hosts:
  - app.test.cluster.local
  http:
  - match:
    - headers:
        x-tenant:
          exact: tenerife
    rewrite:
      authority: app1.default.svc.cluster.local
    route:
      - destination:
          host: cluster-local-gateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100
  - match:
    - match:
      - headers:
          x-tenant:
            exact: lanzarote
    rewrite:
      authority: app2.default.svc.cluster.local
    route:
      - destination:
          host: cluster-local-gateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100